[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200
via_ir = true
gas_limit = 50000000

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'forge-std/=lib/forge-std/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    '@interfaces/=contracts/interfaces/',
    '@core/=contracts/core/',
    '@oracles/=contracts/oracles/',
    '@governance/=contracts/governance/',
    '@vault/=contracts/vault/',
    '@vrf/=contracts/vrf/',
    '@config/=contracts/config/',
    '@math/=contracts/math/',
    '@library/=contracts/library/',
    '@mocks/=contracts/mocks/',
    '@promotions/=contracts/promotions/',
    '@examples/=contracts/examples/',
    '@fees/=contracts/governance/fees/',
    '@utils/=contracts/library/utils/'
]

[profile.ci]
verbosity = 4
